# Build Configuration for Production
# Invory - Performance Optimized Build

flutter:
  build:
    # Enable tree shaking and minification
    tree_shake: true
    minify: true
    
    # Performance optimizations
    enable_web_optimizations: true
    enable_dart_optimizations: true
    
    # Asset optimization
    compress_assets: true
    optimize_assets: true

# Web specific optimizations
web:
  renderer: html
  optimize_for_size: true
  enable_web_optimizations: true

# Android specific optimizations  
android:
  build:
    enable_proguard: true
    enable_r8: true
    minify_enabled: true
    shrink_resources: true

# iOS specific optimizations
ios:
  build:
    enable_bitcode: false
    enable_arm64: true 

targets:
  $default:
    builders:
      build_config|build_config:
        options:
          # Firebase Configuration
          firebase_api_key: $FIREBASE_API_KEY
          firebase_auth_domain: $FIREBASE_AUTH_DOMAIN
          firebase_project_id: $FIREBASE_PROJECT_ID
          firebase_storage_bucket: $FIREBASE_STORAGE_BUCKET
          firebase_messaging_sender_id: $FIREBASE_MESSAGING_SENDER_ID
          firebase_app_id: $FIREBASE_APP_ID
          firebase_measurement_id: $FIREBASE_MEASUREMENT_ID
          
          # VAPID Key
          vapid_key: $VAPID_KEY
