workflows:
  invory_ios_unsigned:
    name: Invory iOS Unsigned Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Analyze code
        script: |
          flutter analyze

      - name: Build iOS release (no codesign)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - flutter_drive.log
