name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build web app
      run: |
        flutter build web \
          --release \
          --web-renderer html \
          --dart-define=VAPID_KEY=BMDdRanIyEdtiUDMzOON8gLELJbQV_lBfhx_rb_Q5WEJ9GFdtV0ObfPvKFnjOyrPFMTwcgW7wh1FBpf0F2bDE4M \
          --dart-define=FLUTTER_WEB_USE_SKIA=false \
          --dart-define=FLUTTER_WEB_AUTO_DETECT=false \
          --dart-define=FLUTTER_WEB_USE_SKIA_RENDERER=false \
          --dart-define=FLUTTER_WEB_USE_CANVASKIT=false
    
    - name: Copy Firebase Service Worker
      run: |
        if [ ! -f "build/web/firebase-messaging-sw.js" ]; then
          echo "📋 Copying Firebase Service Worker..."
          cp web/firebase-messaging-sw.js build/web/firebase-messaging-sw.js
        fi
    
    - name: Verify Service Worker
      run: |
        if [ -f "build/web/firebase-messaging-sw.js" ]; then
          echo "✅ Firebase Service Worker found"
          ls -la build/web/firebase-messaging-sw.js
        else
          echo "❌ Firebase Service Worker not found"
          exit 1
        fi
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy Invory Web App with FCM Notifications'
    
    - name: Verify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔔 Notifiche push configurate"
        echo "🌐 App deployed to: https://robworkhubb.github.io/invory"
        echo "📱 PWA ready for installation"
        echo "🔧 Service Worker: /firebase-messaging-sw.js" 